-- ================================================================
-- Create the tables, editioning views, triggers, and sequences
-- Aplication: 
-- Schema: 
-- Date: 
-- Note: 
-- =================================================================
